- name: Gather Facts
  setup:

- name: miniupnpd installed
  apt: name=upnp state=latest

- name: miniupnpd configured
  template: src=miniupnp.conf.j2 dest=/etc/miniupnpd
  notify:
    - restart miniupnpd

- name: miniupnpd enabled and started
  service: name=miniupnpd state=started enabled=yes

- meta: flush_handlers
